### ISSUE TITLE
Buy SPARTA drop-down in nav menu

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartan-site#85]
Updated 13/08/22:

Added a dropdown menu to the 'Trade SPARTA' CTA on page 1
- A new data type has been added to the CMS: `tradeSpartaLinks` as per this structure:
`{
  "order": 0,
  "label": "Name of the Exchange",
  "URL": "https://urlfortheexchange",
  "icon": "SVG icon path"
}`

On desktop this dropdown menu should drop below the button, on mobile it might need to slide above the button instead to not be inaccessible due to our scroll behavior (better yet, maybe make it open like a modal on mobile)

**Comment by jejopl** [comment]
@SamusElderg done, you can check it out if it's okay for mobile, or if you want to do it inside modal

**Comment by SamusElderg** [comment]
> @SamusElderg done, you can check it out if it's okay for mobile, or if you want to do it inside modal

Looks great good job! 

On mobile, on small devices OR once we have added the icon etc in each section (on most mobile devices) we will run into this edge case though:
![image](https://user-images.githubusercontent.com/26967164/185350756-f1f7a9e6-4791-4ae7-8ed1-4a48b5b22c50.png)
which would normally be fine, however scrolling down for that bottom option will result in sliding past the dropdown content and to the next 'page/section'

So we will either need to make it open upwards using conditional/space logic (like popper.js) or maybe easier to throw it in a modal on mobile (like the hamburger menu). thoughts? happy to pull in popper.js or similar if we go down the "conditionally place the object based on screen space" path!

Also one other behavior suggestion: can we make it close the drop-down in these two instances:
- click/tap outside the dropdown (click anywhere that is not a dropdown option)
- click/tap the "Trade SPARTA" button whilst the dropdown is already open (toggle between true/false)

**Comment by jejopl** [comment]
@SamusElderg it should be good now - I just pushed some changes. Now, the trading links should be moved up, when they are not visible on the screen. The only small thing is that it's not working dynamically on resize. The logic applies when the buttons are shown. So when buttons are visible and you will resize the browser screen, they will not change its position. But if you hide and show them again - they will. 

Let me know if that's okay or if you want me to add on resize event listener

**Comment by SamusElderg** [comment]
> @SamusElderg it should be good now - I just pushed some changes. Now, the trading links should be moved up, when they are not visible on the screen. The only small thing is that it's not working dynamically on resize. The logic applies when the buttons are shown. So when buttons are visible and you will resize the browser screen, they will not change its position. But if you hide and show them again - they will.
> 
> Let me know if that's okay or if you want me to add on resize event listener

This is perfect thankyou!
