### ISSUE TITLE
Migrate the CMS content into the website code

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartan-site#91]
Now that our design is not heavy on media/images, the advantages of using a CMS have been reduced. We should consider moving all content to the repo direct instead of using the CMS.

- Lower complexity for deploys and devs.
- Higher complexity for non-devs who want to edit the website content (we can make this still fairly easy on the repo level by using structures and const files that hold content objects)
- Lower security attack surface

If we do this, lets just make sure every media file we use is an SVG (within reason) to keep the download size small for mobile users & SEO

**Comment by jejopl** [comment]
@SamusElderg what about this one? Do we have a decision?

**Comment by SamusElderg** [comment]
> @SamusElderg what about this one? Do we have a decision?

Hmmm good question, what do you think? I think it probably makes sense to bring all content directly into the website rather than having a cms sitting in between

**Comment by jejopl** [comment]
@SamusElderg yeah, especially when you need to redeploy anyway if you want to change something. I'm wondering, maybe it will be good to use JSON file? This way, most of the people will be able to change/rephrase it

**Comment by SamusElderg** [comment]
> @SamusElderg yeah, especially when you need to redeploy anyway if you want to change something. I'm wondering, maybe it will be good to use JSON file? This way, most of the people will be able to change/rephrase it. And it will be easier to translate it to different languages

I think only use a JSON if its neutral (or better/easier) from a dev perspective. A dev will have to sign off on PRs anyway so i think "complexity of changing content" is probably less important than we were originally making it out to be

I say we go with whatever format works best for devs like yourself

**Comment by SamusElderg** [comment]
Im happy to handle this one @jejopl if you like? I think we should just go simple and bring the content into the specific sections (not a separate json file)

**Comment by jejopl** [comment]
Oh, to be honest I forgot about this one 😄 I'll handle it, you have much more on your plate

**Comment by SamusElderg** [comment]
> Oh, to be honest I forgot about this one 😄 I'll handle it, you have much more on your plate

Well we hadn't really come to a final conclusion on how to proceed so there wasn't really anything to forget 😂 
Also I'm more than happy to chip in, let me know if i can, i promise to not comment out important sections again 😂

**Comment by jejopl** [comment]
Sure you can if you want

**Comment by jejopl** [comment]
done
