### ISSUE TITLE
Community Section | Decrease avatar padding mobile

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartan-site#95]
![image](https://user-images.githubusercontent.com/26967164/209112824-d3138951-53e4-40c7-aadf-2a34d6a24c22.png)

**Comment by jejopl** [comment]
There's a small issue with 4 columns, when the username is too long
![image](https://user-images.githubusercontent.com/32012330/209797907-87b2f622-bb18-4cea-9e69-02fa33f71828.png)

**Comment by SamusElderg** [comment]
> There's a small issue with 4 columns, when the username is too long ![image](https://user-images.githubusercontent.com/32012330/209797907-87b2f622-bb18-4cea-9e69-02fa33f71828.png)

that's okay, we should be truncating that text anyway to prevent accidental (or purposeful) griefing, i think i used something like `.trunc` or `.truncate` in tailwind the other day, this may also need to be combined with some padding in the child or direct parent of the text, I'm happy to have a play with it if you like?

Your example looks a lot better imo, just need to tackle that text issue as you mentioned

**Comment by SamusElderg** [comment]
Lets enforce a `w-20` class or close to it in the parent div (we dont want them to scale up/down with screen sizes) and then apply `truncate` to the text, ill have a quick play with it now and see

**Comment by SamusElderg** [comment]
Yeah i think this will work

320px:
![image](https://user-images.githubusercontent.com/26967164/210197209-6933487b-4d4a-42ac-ba8c-2199739c255f.png)

400px:
![image](https://user-images.githubusercontent.com/26967164/210197237-ef0c58b7-96aa-4e1b-9a09-d0e4300ed331.png)

600px:
![image](https://user-images.githubusercontent.com/26967164/210197248-16b6e4c0-33d5-4624-b79e-572f99153a66.png)

1220px:
![image](https://user-images.githubusercontent.com/26967164/210197284-511ea73a-b36c-4371-acde-21d167ce5ea1.png)

**Comment by SamusElderg** [comment]
Closed with recent commits
