### ISSUE TITLE
Security Section | Strict-set heights for images

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartan-site#96]
Set strict heights for the images. Might also have to tighten the y-padding on one or all of the image files themselves (normalize)

![image](https://user-images.githubusercontent.com/26967164/209118040-0e92c534-5240-4b73-b848-1dd406fe0af4.png)

Can see when this is an issue only really on landscape mobile:
![image](https://user-images.githubusercontent.com/26967164/209118126-e5c81df5-ebe5-4240-bbbd-109c7cf8a5e3.png)

**Comment by jejopl** [comment]
@SamusElderg done
